Dog.create(name: "Benny", age: 2, breed: "French Bulldog")
Dog.create(name: "Barks", age: 5, breed: "Poodle")
Dog.create(name: "Salt", age: 3, breed: "Dashound")
Dog.create(name: "Gliiter", age: 10, breed: "Yorkie")
Dog.create(name: "Billy", age: 7, breed: "Lab")
